import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import PrivyProvider from "@/components/providers/PrivyProvider";
import { NavbarContextProvider } from "@/components/global/Navbar/context";
import NavbarLayout from "@/components/global/Navbar/NavbarLayout";
import { ModalProvider } from "@/components/ui/modal/context";
import ChainSwitchProvider from "@/components/providers/ChainSwitchProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { PriceFeedProvider } from "@/components/providers/PriceFeedProvider";
import { ThemeProvider } from "next-themes";
import HypercertExchangeClientProvider from "@/components/providers/HypercertExchangeClientProvider";
import { AtprotoProvider } from "@/components/providers/AtprotoProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <NuqsAdapter>
            <PrivyProvider>
              <AtprotoProvider>
                <ModalProvider>
                  <PriceFeedProvider>
                    <ChainSwitchProvider>
                      <HypercertExchangeClientProvider>
                        <NavbarContextProvider>
                          <NavbarLayout>{children}</NavbarLayout>
                        </NavbarContextProvider>
                      </HypercertExchangeClientProvider>
                    </ChainSwitchProvider>
                  </PriceFeedProvider>
                </ModalProvider>
              </AtprotoProvider>
            </PrivyProvider>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
