import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Button } from "@/components/ui/button";
import { Sidebar } from "lucide-react";
import Providers from "./_components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased flex h-screen`}
        style={{
          background: `repeating-linear-gradient(
              -55deg,
              var(--background),
              var(--background) 2px,
              color-mix(in oklab, var(--primary) 10%, transparent) 2px,
              color-mix(in oklab, var(--primary) 10%, transparent) 4px
            )`,
        }}
      >
        <Providers>
          <Navbar />
          <main className="flex-1 bg-background m-2 md:ml-0 border border-border rounded-xl relative">
            <Button
              variant="outline"
              className="absolute top-2 left-2"
              size={"icon"}
            >
              <Sidebar size={16} />
            </Button>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
